SHMUDataset:
  metadata_folder: "./data/metadata"
  path: "./data/radar_files"
  input_block_length: 8
  # Number of frames that are predicted
  prediction_block_length: 16
  # Original Image size
  transform_to_mmh: true
  normalization_method: "dBR"
  products: ['dBZ']
  aggregate_vertical: true
  vertical_chunk_size: 2
  erosion_mask: false
  denoise: true
  memmaps: true
augmentations:
  horizontal_flip: true
  vertical_flip: true
  rotate: false
  crop_size: [512, 512]
  edge_nan_padding: 0